### ISSUE TITLE
feat request add optionaltonullsafeoperatorrector

### ISSUE THREAD

**Issue by chrillep** [hammer-tools/laravel-hammer#1]
https://github.com/driftingly/rector-laravel/blob/main/docs/rector_rules_overview.md#optionaltonullsafeoperatorrector

OptionalToNullsafeOperatorRector
Convert simple calls to optional helper to use the nullsafe operator

🔧 configure it!

class: [Rector\Laravel\Rector\PropertyFetch\OptionalToNullsafeOperatorRector](https://github.com/driftingly/rector-laravel/blob/main/src/Rector/PropertyFetch/OptionalToNullsafeOperatorRector.php)

```php
use Rector\Config\RectorConfig;
use Rector\Laravel\Rector\PropertyFetch\OptionalToNullsafeOperatorRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(OptionalToNullsafeOperatorRector::class, [
        OptionalToNullsafeOperatorRector::EXCLUDE_METHODS => ['present'],
    ]);
};
```
↓
```diff
-optional($user)->getKey();
-optional($user)->id;
+$user?->getKey();
+$user?->id;
 // macro methods
 optional($user)->present()->getKey();
 ```

**Comment by rentalhost** [comment]
@chrillep Thanks for your request!

In this case, is your request to suggest replacing `optional()` with null safe operator? Maybe it's a nice addition to the [php-hammer](https://plugins.jetbrains.com/plugin/19515-php-hammer) brother. What do you think?

**Comment by chrillep** [comment]
> In this case, is your request to suggest replacing `optional()` with null safe operator?

hello. yes exactly, i mean optional() is a Laravel function but it works either way for me :)

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Support/Optional.php

https://github.com/laravel/framework/blob/4d126e876d42d8549c420f451badc61a45b6809a/src/Illuminate/Support/helpers.php#L181-L197

**Comment by rentalhost** [comment]
@chrillep Nice! I'll see if I can make this possible in **php-hammer**, so I can cover other frameworks if they have similar functionality.

**Comment by chrillep** [comment]
> @chrillep Nice! I'll see if I can make this possible in **php-hammer**, so I can cover other frameworks if they have similar functionality.

added an issue in php-hammer aswell :) 
https://github.com/hammer-tools/php-hammer/issues/1

**Comment by rentalhost** [comment]
Moved to https://github.com/hammer-tools/php-hammer/issues/1

**Comment by rentalhost** [comment]
Fixed at https://github.com/hammer-tools/php-hammer/issues/1
