### ISSUE TITLE
Not compatible with current PhpStorm Build #PS-232.8660.205, built on July 29, 2023

### ISSUE THREAD

**Issue by CamKem** [hammer-tools/laravel-hammer#3]
Hello, this plugin is now inactive on the current PhpStorm Build #PS-232.8660.205, built on July 29, 2023.

**Comment by rentalhost** [comment]
Hello! This plugin has been discontinued. At some point your features (actually, there's basically only one) will be integrated directly into [**php-hammer**](https://github.com/hammer-tools/php-hammer/issues/17) instead.

**Comment by CamKem** [comment]
@rentalhost Thanks I'll remove it and install php-hammer and look forward to the Laravel features being implemented. I loved laravel-hammer, so hopefully it will be available soon. Thanks again!
